export const tg = window.Telegram.WebApp;

export const state = {
  currentUser: null,
  tgUser: tg.initDataUnsafe && tg.initDataUnsafe.user,
  authUser: JSON.parse(localStorage.getItem('sr_auth_user') || 'null'),
  badgeColor: '#1da1f2',  // цвет по умолчанию для тех, у кого нет своего
  seasonPassData: null,  // { name, endsAt, premiumPrice, levels:{n:{...}}, weeklyQuests:{id:{...}} }
  myPassState: null,  // локальная копия users/{uid}/pass
  timeTrackingStarted: false,
  streakCheckedThisSession: false,
  sessionStartedAt: 0,
  lastFlushedAt: 0,
  postsData: [],
  bannersData: [],
  shopItemsData: [],
  editingBannerId: null,
  booksData: [],
  usersData: [],
  chatsData: [],
  stickersData: [],
  stickerPacksData: [],
  bossData: null,
  bossParticipantsData: {},
  youtubeVideoId: null,
  readBooks: JSON.parse(localStorage.getItem('sr_read') || '[]'),
  bookmarkedBooks: JSON.parse(localStorage.getItem('sr_bookmarks') || '[]'),
  progressStore: JSON.parse(localStorage.getItem('sr_progress') || '{}'),
  streakStore: JSON.parse(localStorage.getItem('sr_streak') || '{"count":0,"lastDate":null}'),
  lastSeenPostsCount: parseInt(localStorage.getItem('sr_last_seen_posts_count') || '0', 10),
  readerFontSize: parseInt(localStorage.getItem('sr_fontsize') || '18', 10),
  chatLastRead: JSON.parse(localStorage.getItem('sr_chat_last_read') || '{}'),
  currentPostId: null,
  viewingUserId: null,
  dailyRewardChecked: false,
  currentBookId: null,
  currentChapters: [],
  currentChapterIndex: 0,
  currentChatId: null,
  activeOverlay: null,
  feedSearchTerm: '',
  bookSearchTerm: '',
  activeGenre: 'Все',
  activeType: 'all',
  sortMode: 'new',
  isAdmin: false,
  editingPostId: null,
  editingBookId: null,
  editingUserPostId: null,
  currentTheme: 'light',
  soundsData: {},
  effectsData: {},
  terrariaData: {},  // доп. фичи темы Terraria (день/ночь, boss hp, пиксель-иконки и т.д.)
  economyData: { dailyEnabled: true, dailyAmount: 10, chapterEnabled: false, chapterAmount: 0, bookEnabled: false, bookAmount: 0, streakEnabled: false, streakAmount: 0, streakEvery: 1, streakMax: 0, eventMultiplier: 1, eventMultiplierUntil: null },
  questsData: [],
  eventsData: [],
  editingEventId: null,
  cardsData: [],
  cardCombosData: [],
  cardPacksData: [],
  editingCardId: null,
  editingComboId: null,
  editingPackId: null,
  heroClassesData: [],
  editingClassId: null,
  cardFramesData: {},
  deckSettings: { deckSize: 30, maxCopies: 2 },
  myCollection: {},
  myDecks: [],
  decksView: 'list',
  editingDeckId: null,
  deckDraft: null,
  inQueue: false,
  matchmakingTimer: null,
  battleListenerAttached: false,
  activeBattleId: null,
  battleData: null,
  mySlot: null,
  selectedAttackerIid: null,
  streakRewardStore: JSON.parse(localStorage.getItem('sr_streak_reward') || '{}'),
  terrariaDayNightTimer: null,
  renderedChatState: { chatId: null, signature: null },
  replyingTo: null,
  editingMessageId: null,
  lastTypingSent: 0,
  typingClearTimer: null,
  editingQuestId: null,
  arenasData: [],
  storyChapters: [],
  storyCleared: {},
  editingStoryChapterId: null,
  storyBossDeckDraft: {},
  storyPendingChapterId: null,
  storyCompletionBannerShown: false,
  storySettings: {},
};
